### ISSUE TITLE
Add support for Visual Studio 2022 build

### ISSUE THREAD

**Issue by gsbelarus** [asfernandes/node-firebird-drivers#114]
We have had an error while compiling the library with node-gyp. And could solve it only by downgrading Microsoft Visual Studio Build Tools to the 2017 version. Are the latest versions supported?

**Comment by asfernandes** [comment]
Please show the errors.

**Comment by gsbelarus** [comment]
Unfortunately, I have already cleared console window contents. There was a
long list of node-gyp messages. It seemed that it tried to find the 2017
version and then reverted to what existed on the PC. In my case, it was the
2019 version of Build Tools. In the end whole process finished with an
error. The problem was solved after removing entirely 2019 Build Tools from
the system and installing the 2017 version.

**Comment by asfernandes** [comment]
GitHub Actions is running in Windows 2019, which have Visual Studio 2019.

**Comment by gsbelarus** [comment]
Ok. It seems that something is wrong with my system configuration. I will recheck. I'm closing the issue.

**Comment by asfernandes** [comment]
I have changed this issue to talk about VS 2022. It's now working in master.
