### ISSUE TITLE
bug: unhandled exception - executeQuery

### ISSUE THREAD

**Issue by Tomas2D** [asfernandes/node-firebird-drivers#139]
The following code throws an unhandled exception, but it should throw just an exception.
In case I correctly use the `executeSingleton` or `executeSingletonAsObject`, it works. But from my perspective, the `executeQuery` should work because the `statement.hasResultSet === true`.

Besides that, I assume that `executeQuery` should work.  Thanks.

```javascript
import { createNativeClient, getDefaultLibraryFilename } from 'node-firebird-driver-native';

async function test() {
	const client = createNativeClient(getDefaultLibraryFilename());
	const attachment = await client.createDatabase(
		'localhost/3050:/tmp/test.fdb',
		{ username: "SYSDBA", password: "masterkey"}
	);
	const transaction = await attachment.startTransaction();

	const statement = await attachment.prepare(transaction, 'SELECT 1 FROM  RDB$DATABASE');
	try {
		// this will throw an unhandled exception
		await statement.executeQuery(transaction);
	} catch {
		console.info('this is never called, but it should be');
	}

	await transaction.commit();
	await attachment.dropDatabase();
	await client.dispose();
}

test().then(() => console.log('Finish...'));
```

**Comment by asfernandes** [comment]
Could you please be more specific?
Why you say that query must use `executeSingleton` or `executeSingletonAsObject` to be correctly?
Why the given code would be problematic?
Isn't it a correct code as the ones used in many tests present in the package?

**Comment by asfernandes** [comment]
Is it because only the returned result set isn't closed?

**Comment by asfernandes** [comment]
Why the catch block should be called?

**Comment by Tomas2D** [comment]
Just run the code, and you will see it. 

This line `await statement.executeQuery(transaction);` triggers the unhandled exception even if it's wrapped in a try/catch block. If I replace the mentioned line with `await statement.executeSingleton(transaction)` works (no error is thrown).

>Why you say that query must use executeSingleton or executeSingletonAsObject to be correctly?
I just assume this because otherwise, the script crashes.

>Why the catch block should be called?
Because it's in the try/catch block.

**Comment by asfernandes** [comment]
Cannot reproduce.
This test correctly print `Finish...` for me.
If you have different result, then you should prepare test case that shows the incorrect behavior.

**Comment by Tomas2D** [comment]
Sorry, the problem was somewhere else.

```typescript
import { createNativeClient, getDefaultLibraryFilename } from 'node-firebird-driver-native';

async function test() {
	const client = createNativeClient(getDefaultLibraryFilename());
	const attachment = await client.createDatabase(
		'localhost/3050:/tmp/test.fdb',
		{ username: "SYSDBA", password: "masterkey"}
	);
	const transaction = await attachment.startTransaction();

	const statement = await attachment.prepare(transaction, 'SELECT 1 FROM  RDB$DATABASE');
	await statement.executeQuery(transaction);
	

        // If I do not add this line, the program prints the following error message and halts (only on Linux Debian 10, not macOS)
        // [Error: Invalid resultset interface]
        await statement.close()

        await transaction.commit();
	await attachment.dropDatabase();
	await client.dispose();
}

test().then(() => console.log('Finish...'));
```

**Comment by asfernandes** [comment]
There is not even method `statement.close()`. It's `dispose`.

**Comment by asfernandes** [comment]
For me too. No problem happens
