### ISSUE TITLE
Invalid format for transaction parameter block

### ISSUE THREAD

**Issue by gsbelarus** [asfernandes/node-firebird-drivers#14]
We use **XpbBuilder** to build a block of transaction params as seen here:

https://github.com/gsbelarus/gdmn/blob/master/packages/gdmn-db/src/fb/utils/fb-utils.ts#L45

Randomly we gets error:

> Error: invalid format for transaction parameter block
> -wrong version of transaction parameter block
> 

May be you have some thoughts on what can be wrong here?

**Comment by asfernandes** [comment]
When you dispose the builder, the buffer returned become invalid. That's how the Firebird API works. So you should clone the buffer or hold the builder active while you are using the buffer.
