### ISSUE TITLE
node-firebird-native-api installation fails

### ISSUE THREAD

**Issue by mariocarro** [asfernandes/node-firebird-drivers#157]
executing "yarn add node-firebird-native-api" fails:

yarn add v1.22.22
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
[1/2] ⠂ node-firebird-native-api
error /home/[...]/node_modules/node-firebird-native-api: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/[...]/node_modules/node-firebird-native-api
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@10.2.0
gyp info using node@20.15.0 | linux | x64
gyp info find Python using Python version 3.11.2 found at "/usr/bin/python3"

gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args '/home/[...]/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/home/[...]/node_modules/node-firebird-native-api/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/home/[...]/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/home/[...]/.cache/node-gyp/20.15.0/include/node/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/home/[...]/.cache/node-gyp/20.15.0',
gyp info spawn args '-Dnode_gyp_dir=/home/[...]/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=/home/[...]/.cache/node-gyp/20.15.0/<(target_arch)/node.lib',
gyp info spawn args '-Dmodule_root_dir=/home/[...]/node_modules/node-firebird-native-api',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/[...]/node_modules/node-firebird-native-api/build'
  CXX(target) Release/obj.target/addon/src/native/fb-native.o
In file included from ../src/native/fb-native.cpp:10:
../src/native/./classes.h: In static member function ‘static void Napi::CustomAsyncWorker::OnWorkComplete(napi_env, napi_status, void*)’:
../src/native/./classes.h:150:46: error: no matching function for call to ‘WrapCallback(Napi::CustomAsyncWorker::OnWorkComplete(napi_env, napi_status, void*)::<lambda()>)’
  150 |                         details::WrapCallback([&] {
      |                         ~~~~~~~~~~~~~~~~~~~~~^~~~~~
  151 |                                 if (self->_error.size() == 0)
      |                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  152 |                                         self->OnOK(env);
      |                                         ~~~~~~~~~~~~~~~~
  153 |                                 else
      |                                 ~~~~          
  154 |                                         self->OnError(env, Error::New(self->_env, self->_error));
      |                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  155 | 
      |                                               
  156 |                                 return nullptr;
      |                                 ~~~~~~~~~~~~~~~
  157 |                         });
      |                         ~~                    
In file included from /home/[...]/node_modules/node-addon-api/napi.h:3293,
                 from ../src/native/fb-native.cpp:8:
/home/[...]/node_modules/node-addon-api/napi-inl.h:85:19: note: candidate: ‘template<class Callable> napi_value__* Napi::details::WrapCallback(napi_env, Callable)’
   85 | inline napi_value WrapCallback(napi_env, Callable callback) {
      |                   ^~~~~~~~~~~~
/home/[...]/node_modules/node-addon-api/napi-inl.h:85:19: note:   template argument deduction/substitution failed:
../src/native/./classes.h:150:46: note:   candidate expects 2 arguments, 1 provided
  150 |                         details::WrapCallback([&] {
      |                         ~~~~~~~~~~~~~~~~~~~~~^~~~~~
  151 |                                 if (self->_error.size() == 0)
      |                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  152 |                                         self->OnOK(env);
      |                                         ~~~~~~~~~~~~~~~~
  153 |                                 else
      |                                 ~~~~          
  154 |                                         self->OnError(env, Error::New(self->_env, self->_error));
      |                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  155 | 
      |                                               
  156 |                                 return nullptr;
      |                                 ~~~~~~~~~~~~~~~
  157 |                         });
      |                         ~~                    
make: *** [addon.target.mk:109: Release/obj.target/addon/src/native/fb-native.o] Error 1
make: Leaving directory '/home/[...]/node_modules/node-firebird-native-api/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack at ChildProcess.<anonymous> (/home/[...]/node_modules/node-gyp/lib/build.js:216:23)
gyp ERR! System Linux 6.1.0-27-amd64
gyp ERR! command "/home/[...]/.nvm/versions/node/v20.15.0/bin/node" "/home/[...]/node_modules/node-firebird-native-api/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/[...]/node_modules/node-firebird-native-api
gyp ERR! node -v v20.15.0
gyp ERR! node-gyp -v v10.2.0
gyp ERR! not ok

**Comment by asfernandes** [comment]
Please try the just released version.
