### ISSUE TITLE
createNativeClient fails in mac OS

### ISSUE THREAD

**Issue by mreis1** [asfernandes/node-firebird-drivers#29]
Cannot load Firebird client library: 'libfbclient.dylib'.
Error: Cannot load Firebird client library: 'libfbclient.dylib'.

Due to:
https://forum.lazarus.freepascal.org/index.php?topic=8128.0

**Comment by asfernandes** [comment]
@mreis1 if it's due to the problem you pointed out, fix seems out of scope of that library, no?

Isn't a installation problem of Firebird?

**Comment by mreis1** [comment]
I completely agree with you @asfernandes but I would still state the known issue in the README file of this project and point out the solution. 

**For example:** 

**Warning for MacOS users**
Make sure to create a symlink of your firebird installation into **/usr/local/lib/libfbclient.dylib**
You can do so by running `sudo ln -s /Library/Frameworks/Firebird.framework/Versions/A/Firebird /usr/local/lib/libfbclient.dylib`

If you don't do this, you will not be able to use this library due to: 

```
Cannot load Firebird client library: 'libfbclient.dylib'.
Error: Cannot load Firebird client library: 'libfbclient.dylib'. 

```


What do you think?

**Comment by asfernandes** [comment]
Ok, will do. Could you please also create a ticket in Firebird tracker http://tracker.firebirdsql.org ?

**Comment by mreis1** [comment]
Done: http://tracker.firebirdsql.org/browse/CORE-6117
