### ISSUE TITLE
Result set rows header

### ISSUE THREAD

**Issue by pupupulp** [asfernandes/node-firebird-drivers#30]
Is there any way to return headers along with the result set rows or format the result set rows along with the header?

something like this

{
  header1: value1,
  header2: value2,
  header3: value3
}

the rows i get only have

{
  value1,
  value2,
  value3
}

**Comment by asfernandes** [comment]
I suppose you want `[{ column1: value1, column2: value2 }, ...]` instead of `[[value1, value2], ...]` ?

**Comment by pupupulp** [comment]
yes yes thats itSent from my Samsung Galaxy smartphone.
-------- Original message --------From: Adriano dos Santos Fernandes <notifications@github.com> Date: 8/8/19  20:35  (GMT+08:00) To: asfernandes/node-firebird-drivers <node-firebird-drivers@noreply.github.com> Cc: Eagan Martin <mece.martinece@gmail.com>, Author <author@noreply.github.com> Subject: Re: [asfernandes/node-firebird-drivers] Result set rows header (#30) I suppose you want [{ column1: value1, column2: value2 }, ...] instead of [[value1, value2], ...] ?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/asfernandes/node-firebird-drivers/issues/30?email_source=notifications\u0026email_token=AJF4SYXWJQOMFRQCUB42HXLQDQHJFA5CNFSM4IKJHK6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD33O5LI#issuecomment-519499437",
"url": "https://github.com/asfernandes/node-firebird-drivers/issues/30?email_source=notifications\u0026email_token=AJF4SYXWJQOMFRQCUB42HXLQDQHJFA5CNFSM4IKJHK6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD33O5LI#issuecomment-519499437",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by pupupulp** [comment]
it would be a lot of help if we could get the result in that format, i checked through the code and examples but i cant seem to find how to do it using entirely the library, right now we created a separate array for the keys and used reduce function but it seems slow and takes a lot of processing time specially when the result set is large

**Comment by mreis1** [comment]
I must agree that this would be very helpful, specially if we rely on wildcards to fetch all the columns from a given table.

A suggestion would be to pass a "options object" to methods such as:
![2019-10-09_10-21-40](https://user-images.githubusercontent.com/1719667/66464072-99e1c600-ea7e-11e9-9202-fcdfd9600c9f.png)

**Comment by mreis1** [comment]
@asfernandes do you have any thoughts on this? 

There's an implementation for this on xdenders lib. Maybe this can inspire you on how to implement this piece of functionality. 

https://github.com/xdenser/node-firebird-libfbclient/blob/master/src/fb-bindings-fbresult.cc#L585

I realize that there's an issue with my initial proposal. 
Since executeQuery doesn't fetch results, the json propery should be set at 
`resultSet.fetch({fetchSize?: number; json?: boolean})`
