### ISSUE TITLE
Command failed with exit code 3221225477

### ISSUE THREAD

**Issue by gsbelarus** [asfernandes/node-firebird-drivers#31]
When using `getPlanAsync()` we are receiving the error. `getPlanSync()` works well at the same time.

**Comment by asfernandes** [comment]
Show the code, please.

**Comment by gsbelarus** [comment]
Please, consider this PR https://github.com/asfernandes/node-firebird-drivers/pull/32.

Async getPlan() is not working, the test falls with error.

**Comment by gsbelarus** [comment]
Though in the considered PR we get plan for `INSERT` statement, the same result would be obtained for an `SELECT` statement too.

**Comment by gsbelarus** [comment]
Can you confirm the issue?

**Comment by asfernandes** [comment]
From what I understand, the problem happens when Firebird API methods returning string returns a `nullptr`.

**Comment by gsbelarus** [comment]
So, `async` and `sync` versions of `getPlan` use different API calls?

**Comment by gsbelarus** [comment]
Is it possible to find a reason of the problem and fix it. I have put a small donation )) Thanks anyway!

**Comment by asfernandes** [comment]
I will look deep into the problem. It seems to require changes in the cloop-generator to change the generated code.

Thank you for the donation. :)

**Comment by asfernandes** [comment]
Fix is committed in master. Can you test it before I release it in npm?

**Comment by gsbelarus** [comment]
Is it possible to publish through NPM as beta version? It would be much easier for me to test then.

**Comment by asfernandes** [comment]
Published as 1.0.1-beta.1.

**Comment by gsbelarus** [comment]
Installed latest beta and tested. All works as expected. Thanks.

**Comment by asfernandes** [comment]
I just published 1.0.1.
