### ISSUE TITLE
Probable Memory Leak

### ISSUE THREAD

**Issue by AdrianoAzuos** [asfernandes/node-firebird-drivers#38]
I believe this issue is occurring in fblib, specifically in the resultset

I initially believed it to be in my implementation that something was going wrong, but I did some testing and anyway the memory consumption increases and the garbage collector can't restore it

**Comment by asfernandes** [comment]
Test case, please.

**Comment by asfernandes** [comment]
If there is no reproducible test case, I'll need to close this.
