### ISSUE TITLE
resultSet.fetch() hangs if I execute read query before insert query is committed (insert and read must use same attachment)

### ISSUE THREAD

**Issue by mreis1** [asfernandes/node-firebird-drivers#40]
```
export async function run({log, connect}) {
    try {
        const attachment = await connect() as Attachment;
        const transaction = await attachment.startTransaction({
            accessMode: 'READ_ONLY',
            autoCommit: false,
            isolation: TransactionIsolation.READ_COMMITTED,
        });
        const transaction2 = await attachment.startTransaction({
            accessMode: 'READ_WRITE'
        });


        // >> INSERT SOMETHING
        let query = `INSERT INTO TEST_TABLE(ID, NAME) VALUES (?, ?)`;
        let r = await attachment.executeReturning(
            transaction2,
            query,
            [Date.now(), 'TEST_NAME']
        );

        // >> COMMIT 2s LATER
        setTimeout(async () => {
            try {
                log('Running transaction2.commitRetaining()');
                await transaction2.commit();
                log('Committed transaction that was hanging');
            } catch (err) {
                log('Error failed to commit parallel transaction');
            }
        }, 2000);


        // READ AS SOON AS POSSIBLE (while previous commit didn't took place)
        query = `SELECT COUNT(*) FROM TEST_TABLE`;
        log('Reading as soon as possible: ' + query);
        let resultSet3 = await attachment.executeQuery(
            transaction, query);
        log('Read completed. Fetching results....');
        let rows3 = await resultSet3.fetch();
        log('Fetch completed', rows3);
        log('Closing resultSet3', rows3);
        await resultSet3.close();
        log('Closed resultSet3');

        log(`ResultSet3: `, {resultSet3: JSON.stringify(rows3)});
        await transaction.commit();

        // DISCONNECT Later
        setTimeout(async () => {
            log('Disconnecting...');
            await attachment.disconnect();
            log('Disconnected!!');
        }, 3000)

    } catch (err) {
        log(err);
    }
}

```

Outputs:

DB2_005    Reading as soon as possible: SELECT COUNT(*) FROM TEST_TABLE []
DB2_005    Read completed. Fetching results.... []
DB2_005    Running transaction2.commitRetaining() []

If I run the same thing but in different attachments, it works: 

DB2_005    Reading as soon as possible: SELECT COUNT(*) FROM TEST_TABLE []
DB2_005    Read completed. Fetching results.... []
DB2_005    Running transaction2.commitRetaining() []
DB2_005    Committed transaction that was hanging []
DB2_005    Fetch completed [ [ [ 16 ] ] ]
DB2_005    Closing resultSet3 [ [ [ 16 ] ] ]
DB2_005    Closed resultSet3 []
DB2_005    ResultSet3:  [ { resultSet3: '[[16]]' } ]
Finish...
DB2_005    Disconnecting... []
DB2_005    Disconnected!! []

**Comment by asfernandes** [comment]
Looks like way Firebird works. Try transaction options:

```
	readCommittedMode?: 'NO_RECORD_VERSION' | 'RECORD_VERSION';
	waitMode?: 'NO_WAIT' | 'WAIT';
```

**Comment by mreis1** [comment]
Thank you Adriano. 

Switching the `transaction` to 'NO_WAIT' will throw a deadlock (line 37). 
I managed to solve this by forcing readCommitedMode to 'RECORD_VERSION' (looks like NO_RECORD_VERSION is the default value). 

So updating line 4 to: 
```
const transaction = await attachment.startTransaction({
            accessMode: 'READ_ONLY',
            autoCommit: false,
            isolation: TransactionIsolation.READ_COMMITTED,
            waitMode: 'NO_WAIT',
            readCommittedMode: 'RECORD_VERSION'
}); 
```
fixed it. Now reading won't hang as it did before.

DB2_005    Reading as soon as possible: SELECT COUNT(*) FROM TEST_TABLE []
DB2_005    Read completed. Fetching results.... []
DB2_005    Fetch completed [ [ [ 23 ] ] ]
DB2_005    Closing resultSet3 [ [ [ 23 ] ] ]
DB2_005    Closed resultSet3 []
DB2_005    ResultSet3:  [ { resultSet3: '[[23]]' } ]
Finish...
DB2_005    Running transaction2.commitRetaining() []
DB2_005    Committed transaction that was hanging []
DB2_005    Disconnecting... []
DB2_005    Disconnected!! []

But I still have a question on this subject.
Assuming my previous configuration, where 2 transactions (READ_ONLY and READ_WRITE) were generated. 

Shouldn't line 37 get resolved once line 26 is executed? 

Here's my expected log: 


DB2_005    Reading as soon as possible: SELECT COUNT(*) FROM TEST_TABLE []

// Hang starts here because transaction2 is not yet commited
DB2_005    Running transaction2.commitRetaining() []
DB2_005    Committed transaction that was hanging []

// Commit took place, line 37 would get resolved get a log that looks like this: <<<

DB2_005    Read completed. Fetching results.... []
DB2_005    Fetch completed [ [ [ 23 ] ] ]
DB2_005    Closing resultSet3 [ [ [ 23 ] ] ]
DB2_005    Closed resultSet3 []
DB2_005    ResultSet3:  [ { resultSet3: '[[23]]' } ]
Finish...
DB2_005    Disconnecting... []
DB2_005    Disconnected!! []

**Comment by asfernandes** [comment]
I still believe this is standard Firebird behaviour, it could be tested with ISQL to see if there is difference.
