### ISSUE TITLE
Charset UTF8

### ISSUE THREAD

**Issue by jucapablanca** [asfernandes/node-firebird-drivers#50]
Currently, the library does not have a way to use a charset other than utf8, which makes it very difficult to use in Latin countries, with accentuation in the language. Thanks for listening.

**Comment by asfernandes** [comment]
Not strings are UTF8. Why do you want to use other charsets as client charset?

**Comment by jucapablanca** [comment]
Currently, my clients' databases use "ISO8859_1" charset, and have records with special characters in this format. So when I use this library, the information read or saved is incorrect.

**Comment by jucapablanca** [comment]
Example this information "áéíóúãç" is saved "Ã¡Ã©Ã­Ã³ÃºÃ£Ã§"

**Comment by asfernandes** [comment]
So your are doing something wrong, for example, using NONE charset in the columns. The client charset (which this driver uses UTF8) is *the client charset* and is transliterated to the columns charset.
