### ISSUE TITLE
Docker image with FB node application

### ISSUE THREAD

**Issue by marcin-bury** [asfernandes/node-firebird-drivers#92]
Hello

Excuse me, if this is not a proper place to ask that question, but did not find a better one.
Has anybody tried to create docker image with application based on this firebird drivers utilizing node/alpine docker images 
I'm fairly new to node itself, so I will appreciate any clues (including sample docker files or compose files)

TIA
Marcin

**Comment by asfernandes** [comment]
There is docker images for Firebird and for node. Generally, they are different images (server, client).

But you can customize and join them to use embedded.
